nnoremap <leader>gd :YcmCompleter GoTo<cr>
nnoremap <leader>gi :YcmCompleter GoToImplementation<cr>
nnoremap <leader>qf :YcmCompleter FixIt<cr>
nnoremap <space>o :YcmCompleter GoToDocumentOutline<cr>
nnoremap <leader>gr :YcmCompleter GoToReferences<cr>
nnoremap <leader>oi :YcmCompleter OrganizeImports<cr>
nnoremap <leader>gc :YcmCompleter GoToCallers<cr>
nnoremap <leader>ge :YcmCompleter GoToCallees<cr>
nnoremap <leader>rn :YcmCompleter RefactorRename<cr>
nnoremap K :YcmCompleter GetDoc<cr>
